'''

http://projecteuler.net/problem=29

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

'''

def main
	results = []

	for i in 2..100
		for j in 2..100
			results.push(i**j)
		end
	end

	puts results.uniq.length
end

main()